// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SINAC.Capacitacion.Curso1.API.Models
{
    public partial class CapacitacionContext : DbContext
    {
        public CapacitacionContext()
        {
        }

        public CapacitacionContext(DbContextOptions<CapacitacionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Agents>(entity =>
            {
                entity.HasKey(e => e.AgentCode)
                    .HasName("PK__AGENTS__843A8BBAF5D26FC8");

                entity.ToTable("AGENTS");

                entity.Property(e => e.AgentCode)
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("AGENT_CODE")
                    .IsFixedLength();

                entity.Property(e => e.AgentName)
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("AGENT_NAME")
                    .IsFixedLength();

                entity.Property(e => e.Commission)
                    .HasColumnType("numeric(10, 2)")
                    .HasColumnName("COMMISSION");

                entity.Property(e => e.Country)
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("COUNTRY");

                entity.Property(e => e.PhoneNo)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("PHONE_NO")
                    .IsFixedLength();

                entity.Property(e => e.WorkingArea)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("WORKING_AREA")
                    .IsFixedLength();
            });

            modelBuilder.Entity<Customer>(entity =>
            {
                entity.HasKey(e => e.CustCode)
                    .HasName("PK__CUSTOMER__8393C4A15A869D32");

                entity.ToTable("CUSTOMER");

                entity.Property(e => e.CustCode)
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("CUST_CODE");

                entity.Property(e => e.AgentCode)
                    .IsRequired()
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("AGENT_CODE")
                    .IsFixedLength();

                entity.Property(e => e.CustCity)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("CUST_CITY")
                    .IsFixedLength();

                entity.Property(e => e.CustCountry)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("CUST_COUNTRY");

                entity.Property(e => e.CustName)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("CUST_NAME");

                entity.Property(e => e.Grade).HasColumnName("GRADE");

                entity.Property(e => e.OpeningAmt)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("OPENING_AMT");

                entity.Property(e => e.OutstandingAmt)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("OUTSTANDING_AMT");

                entity.Property(e => e.PaymentAmt)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("PAYMENT_AMT");

                entity.Property(e => e.PhoneNo)
                    .IsRequired()
                    .HasMaxLength(17)
                    .IsUnicode(false)
                    .HasColumnName("PHONE_NO");

                entity.Property(e => e.ReceiveAmt)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("RECEIVE_AMT");

                entity.Property(e => e.WorkingArea)
                    .IsRequired()
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .HasColumnName("WORKING_AREA");

                entity.HasOne(d => d.AgentCodeNavigation)
                    .WithMany(p => p.Customer)
                    .HasForeignKey(d => d.AgentCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CUSTOMER__AGENT___267ABA7A");
            });

            modelBuilder.Entity<Orders>(entity =>
            {
                entity.HasKey(e => e.OrdNum)
                    .HasName("PK__ORDERS__27AB607C750F86E3");

                entity.ToTable("ORDERS");

                entity.Property(e => e.OrdNum)
                    .HasColumnType("numeric(6, 0)")
                    .HasColumnName("ORD_NUM");

                entity.Property(e => e.AdvanceAmount)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("ADVANCE_AMOUNT");

                entity.Property(e => e.AgentCode)
                    .IsRequired()
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("AGENT_CODE")
                    .IsFixedLength();

                entity.Property(e => e.CustCode)
                    .IsRequired()
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("CUST_CODE");

                entity.Property(e => e.OrdAmount)
                    .HasColumnType("numeric(12, 2)")
                    .HasColumnName("ORD_AMOUNT");

                entity.Property(e => e.OrdDate)
                    .HasColumnType("date")
                    .HasColumnName("ORD_DATE");

                entity.Property(e => e.OrdDescription)
                    .IsRequired()
                    .HasMaxLength(60)
                    .IsUnicode(false)
                    .HasColumnName("ORD_DESCRIPTION");

                entity.HasOne(d => d.AgentCodeNavigation)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.AgentCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ORDERS__AGENT_CO__2A4B4B5E");

                entity.HasOne(d => d.CustCodeNavigation)
                    .WithMany(p => p.Orders)
                    .HasForeignKey(d => d.CustCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ORDERS__CUST_COD__29572725");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}