// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SINAC.Capacitacion.Curso1.API.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Orders = new HashSet<Orders>();
        }

        public string CustCode { get; set; }
        public string CustName { get; set; }
        public string CustCity { get; set; }
        public string WorkingArea { get; set; }
        public string CustCountry { get; set; }
        public int? Grade { get; set; }
        public decimal OpeningAmt { get; set; }
        public decimal ReceiveAmt { get; set; }
        public decimal PaymentAmt { get; set; }
        public decimal OutstandingAmt { get; set; }
        public string PhoneNo { get; set; }
        public string AgentCode { get; set; }

        public virtual Agents AgentCodeNavigation { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}