// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SINAC.Capacitacion.Curso1.API.Models
{
    public partial class Orders
    {
        public decimal OrdNum { get; set; }
        public decimal OrdAmount { get; set; }
        public decimal AdvanceAmount { get; set; }
        public DateTime OrdDate { get; set; }
        public string CustCode { get; set; }
        public string AgentCode { get; set; }
        public string OrdDescription { get; set; }

        public virtual Agents AgentCodeNavigation { get; set; }
        public virtual Customer CustCodeNavigation { get; set; }
    }
}